REM   Script: Activity8
REM   Activity8

SELECT MAX(PURCHASE_AMOUNT) AS "MAX_PURCHASE_AMT",CUSTOMER_ID FROM orders GROUP BY CUSTOMER_ID ORDER BY CUSTOMER_ID;

SELECT MAX(PURCHASE_AMOUNT) AS "MAX_AMT", SALESMAN_ID FROM orders WHERE ORDER_DATE='17-AUG-12' GROUP BY SALESMAN_ID;

SELECT MAX(PURCHASE_AMOUNT) AS "MAX_AMT",CUSTOMER_ID,ORDER_DATE FROM orders GROUP BY CUSTOMER_ID,ORDER_DATE HAVING MAX(PURCHASE_AMOUNT) IN(2030, 3450, 5760, 6000);

